name: idt_chat
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  easy_localization: 3.0.2
  freezed_annotation: 2.2.0
  flutter_lorem: 2.0.0
  flutter_riverpod: 2.3.6
  go_router: 8.0.5
  json_annotation: 4.8.1
  logger: 1.4.0
  rxdart: 0.27.7
  shared_preferences: '>=2.0.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: 2.4.5
  fake_async: 1.3.1
  freezed: 2.3.5
  flutter_lints: 2.0.0
  json_serializable: 6.7.0
  mocktail: 0.3.0
  test: 1.24.1

flutter:

  uses-material-design: true
  assets:
    - assets/json/
    - assets/translations/